---
### terminate AWS EC/2 instances
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - name: Stop sandbox instances
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-05e2b5250a6ba6c69'
      - 'i-0f5eee45ce8687eb6'
    region: "ap-south-1"
  tasks:
    - name: Stop the sandbox instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: absent
        wait: True
        vpc_subnet_id: "subnet-0b6bbb7aa2055a6d8"
        assign_public_ip: yes
